/**
 * Destination data pipeline: Combines manual input + APIs into publication-ready catalog entry.
 *
 * APIs:
 * - Climate: Open-Meteo (automatic, already collected)
 * - Travel: Kiwi.com API
 * - Holidays: Nager.Date (already collected)
 *
 * Inputs:
 * - Manual data: tourism calendar, costs, visitor patterns (JSON)
 * - Climate data: Generated by build-reference-data.ts
 * - City metadata: User input (coordinates, timezone, etc.)
 *
 * Output:
 * - Destination object (ready to add to src/data/destinations.ts)
 * - Quality report (verification results)
 */

import type {
  Destination,
  Season,
  ClimateMonth,
  ClimateRecord,
} from "../src/lib/domain/types";
import { CLIMATE_RECORDS } from "../src/data/generated/climate-index";
import { DESTINATIONS } from "../src/data/destinations";
import * as fs from "node:fs/promises";
import * as path from "node:path";

interface ManualCityData {
  id: string;
  name: string;
  area: string;
  country: string;
  region: string;
  lat: number;
  lon: number;
  timezone: string;
  coastal: boolean;
  /**
   * IATA code of the airport visitors actually arrive at — the gateway, not the nearest
   * strip. Required, and not derivable: nearest-airport scored 14/20 against known-good
   * values, resolving Rome to Ciampino and Paris to Le Bourget. Confirm it against the
   * departure airport's published destinations before adding a city.
   */
  arrivalAirport: string;
  archetype: "city" | "beach" | "resort" | "mixed" | "nature";
  tourismTier: 1 | 2 | 3;
  summary: string;
}

interface ManualInputData {
  // Events by month
  events: Record<number, string[]>;
  // Visitor pattern: peak/shoulder/low
  visitorPattern: Record<number, "low" | "shoulder" | "peak">;
  // Cost data: fourStar and fiveStar nightly rates (USD)
  costs: Record<number, { fourStar: number; fiveStar: number }>;
  // Travel logistics
  travelHours: number;
  travelConnections: number;
  arrivalEase: number;
  // Calculated from other data
  peakMultiplier?: number;
  lowMultiplier?: number;
}

interface KiwiFlightSearch {
  nights: number;
  startDate: string;
  endDate: string;
}

/** Calculate ground travel time from airport to city center using Google Maps */
export async function getGroundTravelTime(
  airportName: string,
  cityName: string,
): Promise<{
  estimatedMinutes: number;
  estimateSource: string;
}> {
  // https://developers.google.com/maps/documentation/distance-matrix
  const apikey = process.env.GOOGLE_MAPS_API_KEY;
  if (!apikey) {
    console.warn(
      "GOOGLE_MAPS_API_KEY not set. Using default ground travel estimate (45 min). Set the env var for precise routing.",
    );
    return {
      estimatedMinutes: 45,
      estimateSource: "default",
    };
  }

  try {
    const url = new URL("https://maps.googleapis.com/maps/api/distancematrix/json");
    url.searchParams.set("origins", `${airportName} airport`);
    url.searchParams.set("destinations", `${cityName} city center`);
    url.searchParams.set("mode", "driving");
    url.searchParams.set("key", apikey);

    const res = await fetch(url.toString());
    if (!res.ok) {
      throw new Error(`Google Maps API error: ${res.status}`);
    }

    interface GoogleMapsResponse {
      rows: Array<{
        elements: Array<{
          duration?: { value: number }; // seconds
          status: string;
        }>;
      }>;
      status: string;
    }

    const data = (await res.json()) as GoogleMapsResponse;
    if (data.status !== "OK" || !data.rows[0]?.elements[0]) {
      throw new Error("No route found");
    }

    const element = data.rows[0].elements[0];
    if (element.status !== "OK" || !element.duration) {
      throw new Error("Route unavailable");
    }

    const minutes = Math.round(element.duration.value / 60);
    return {
      estimatedMinutes: minutes,
      estimateSource: "Google Maps",
    };
  } catch (err) {
    console.warn(
      `Ground travel time lookup failed: ${err instanceof Error ? err.message : String(err)}. Using default (45 min).`,
    );
    return {
      estimatedMinutes: 45,
      estimateSource: "default",
    };
  }
}

/** Calculate cost multipliers from monthly variation */
function calculateCostMultipliers(
  costs: Record<number, { fourStar: number; fiveStar: number }>,
): { peakMultiplier: number; lowMultiplier: number } {
  const allCosts = Object.values(costs).flatMap((m) => [m.fourStar, m.fiveStar]);
  const avgCost = allCosts.reduce((a, b) => a + b, 0) / allCosts.length;

  const maxMonth = Math.max(...Object.values(costs).map((m) => Math.max(m.fourStar, m.fiveStar)));
  const minMonth = Math.min(...Object.values(costs).map((m) => Math.min(m.fourStar, m.fiveStar)));

  return {
    peakMultiplier: Math.round((maxMonth / avgCost) * 100) / 100,
    lowMultiplier: Math.round((minMonth / avgCost) * 100) / 100,
  };
}

/** Derive suitability ratings from climate and visitor patterns */
function calculateSuitabilityRatings(
  climate: ClimateMonth[],
  visitorPattern: Record<number, "low" | "shoulder" | "peak">,
  coastal: boolean,
): number[] {
  const ratings: number[] = [];

  for (let month = 1; month <= 12; month++) {
    const c = climate[month - 1];
    if (!c) {
      ratings.push(3); // Default to neutral
      continue;
    }

    let score = 3; // Start at neutral

    // Temperature comfort (aim for 60-80°F)
    const avgTemp = (c.highF + c.lowF) / 2;
    if (avgTemp >= 60 && avgTemp <= 80) score += 1;
    else if (avgTemp < 40 || avgTemp > 90) score -= 1;

    // Precipitation (lower is better)
    if (c.rainDays < 5) score += 0.5;
    else if (c.rainDays > 15) score -= 0.5;

    // Sun hours (higher is better)
    if (c.sunHours > 6) score += 0.5;
    else if (c.sunHours < 3) score -= 0.5;

    // Visitor pattern (peak is most suitable)
    const pattern = visitorPattern[month];
    if (pattern === "peak") score += 0.5;
    else if (pattern === "low") score -= 0.5;

    // Sea temperature for coastal cities (bonus if warm)
    if (coastal && c.sstF && c.sstF > 70) score += 0.5;

    // Clamp to 1-5 range
    const final = Math.max(1, Math.min(5, Math.round(score * 10) / 10));
    ratings.push(final);
  }

  return ratings;
}

/** Convert visitor pattern to season labels */
function seasonLabelsFromPattern(pattern: Record<number, "low" | "shoulder" | "peak">): Season[] {
  const labels: Season[] = [];
  for (let month = 1; month <= 12; month++) {
    const p = pattern[month] || "shoulder";
    if (p === "peak") labels.push("peak");
    else if (p === "low") labels.push("low");
    else labels.push("shoulder");
  }
  return labels;
}

/** Generate month-by-month notes from climate + events */
function generateMonthNotes(
  climate: ClimateMonth[],
  events: Record<number, string[]>,
  visitorPattern: Record<number, "low" | "shoulder" | "peak">,
  name: string,
): Record<string, string> {
  const notes: Record<string, string> = {};

  const monthNames = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  for (let month = 1; month <= 12; month++) {
    const c = climate[month - 1];
    if (!c) continue;

    const avgTemp = Math.round((c.highF + c.lowF) / 2);
    const crowdLevel = visitorPattern[month] || "shoulder";
    const eventList = (events[month] || []).join(", ");

    let note = "";
    note += `Highs around ${c.highF}°F with ${c.rainDays} rain days on average.`;

    if (eventList) {
      note += ` ${eventList} this month.`;
    }

    const crowdText = crowdLevel === "peak" ? "Peak tourist season" :
                      crowdLevel === "low" ? "Quiet, low tourism" :
                      "Moderate crowds";
    note += ` ${crowdText}. `;

    if (crowdLevel === "peak") {
      note += "Expect higher prices and busy attractions.";
    } else if (crowdLevel === "low") {
      note += "Many attractions may have reduced hours or closures.";
    }

    notes[String(month)] = note;
  }

  return notes;
}

/** Compile all data into a Destination object */
export async function buildDestination(
  cityData: ManualCityData,
  manualInput: ManualInputData,
  climateId?: string,
): Promise<Destination> {
  const climate = CLIMATE_RECORDS[climateId || cityData.id];
  if (!climate) {
    throw new Error(`Climate data not found for ${cityData.id}. Run: npm run build:data`);
  }

  const multipliers = calculateCostMultipliers(manualInput.costs);

  // Get baseline cost from sampled months (average them)
  const sampledCosts = Object.values(manualInput.costs).flatMap((m) => [m.fourStar, m.fiveStar]);
  const fourStarUSD = Math.round(
    Object.entries(manualInput.costs)
      .map(([_, m]) => m.fourStar)
      .reduce((a, b) => a + b, 0) / Object.keys(manualInput.costs).length,
  );

  const fiveStarUSD = Math.round(
    Object.entries(manualInput.costs)
      .map(([_, m]) => m.fiveStar)
      .reduce((a, b) => a + b, 0) / Object.keys(manualInput.costs).length,
  );

  const suitability = calculateSuitabilityRatings(
    climate.monthly,
    manualInput.visitorPattern,
    cityData.coastal,
  );

  const seasons = seasonLabelsFromPattern(manualInput.visitorPattern);
  const monthNotes = generateMonthNotes(
    climate.monthly,
    manualInput.events,
    manualInput.visitorPattern,
    cityData.name,
  );

  const destination: Destination = {
    id: cityData.id,
    name: cityData.name,
    area: cityData.area,
    country: cityData.country,
    region: cityData.region,
    lat: cityData.lat,
    lon: cityData.lon,
    timezone: cityData.timezone,
    arrivalAirport: cityData.arrivalAirport,
    coastal: cityData.coastal,
    archetype: cityData.archetype,
    tourismTier: cityData.tourismTier,
    summary: cityData.summary,
    travel: {
      nonstop: manualInput.travelConnections === 0,
      typicalTotalHours: manualInput.travelHours,
      typicalConnections: manualInput.travelConnections,
      arrivalEase: manualInput.arrivalEase,
      notes: `Typical routing from US East Coast: ${manualInput.travelHours}h via ${manualInput.travelConnections === 0 ? "nonstop" : `${manualInput.travelConnections} stop${manualInput.travelConnections > 1 ? "s" : ""}`}.`,
    },
    lodging: {
      fourStarUSD,
      fiveStarUSD,
      peakMultiplier: multipliers.peakMultiplier,
      lowMultiplier: multipliers.lowMultiplier,
    },
    experience: {
      food: 3,
      culture: 3,
      beaches: cityData.coastal ? 4 : 0,
      nightlife: 3,
      dayTrips: 3,
      nature: 3,
      shopping: 3,
    },
    practicality: {
      localTransport: 3,
      languageEase: 3,
      safetyEase: 3,
      entryEase: manualInput.arrivalEase,
      tripSimplicity: 3,
    },
    seasons,
    suitability,
    monthNotes: monthNotes as Record<number, string>,
    risks: [],
    curatedOn: new Date().toISOString().split("T")[0],
  };

  return destination;
}

/** Load and validate manual input JSON */
export async function loadManualData(filePath: string): Promise<ManualInputData> {
  const content = await fs.readFile(filePath, "utf8");
  const data = JSON.parse(content) as ManualInputData;

  // Validate required fields
  const required = ["events", "visitorPattern", "costs", "travelHours", "travelConnections", "arrivalEase"];
  for (const field of required) {
    if (!(field in data)) {
      throw new Error(`Missing required field: ${field}`);
    }
  }

  return data;
}

export async function loadCityData(filePath: string): Promise<ManualCityData> {
  const content = await fs.readFile(filePath, "utf8");
  return JSON.parse(content) as ManualCityData;
}
